import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const base = 'https://vibes.consulting'
  
  // Main pages
  const mainPages = [
    { url: '', priority: 1, changeFrequency: 'daily' as const },
    { url: '/about', priority: 0.8, changeFrequency: 'monthly' as const },
    { url: '/contact', priority: 0.8, changeFrequency: 'monthly' as const },
    { url: '/faq', priority: 0.7, changeFrequency: 'monthly' as const },
  ]

  // Services pages
  const servicesPages = [
    { url: '/services', priority: 0.9, changeFrequency: 'weekly' as const },
    { url: '/services/business-flow', priority: 0.85, changeFrequency: 'weekly' as const },
    { url: '/services/ai-integration', priority: 0.85, changeFrequency: 'weekly' as const },
    { url: '/services/culture-optimization', priority: 0.85, changeFrequency: 'weekly' as const },
  ]

  // Packages pages
  const packagesPages = [
    { url: '/packages', priority: 0.9, changeFrequency: 'weekly' as const },
    { url: '/packages/flow-check', priority: 0.85, changeFrequency: 'weekly' as const },
    { url: '/packages/flow-rebuild', priority: 0.85, changeFrequency: 'weekly' as const },
    { url: '/packages/vibe-partnership', priority: 0.85, changeFrequency: 'weekly' as const },
  ]

  // Case studies
  const caseStudiesPages = [
    { url: '/case-studies', priority: 0.8, changeFrequency: 'monthly' as const },
    { url: '/case-studies/consulting-collective', priority: 0.75, changeFrequency: 'monthly' as const },
    { url: '/case-studies/retail-testing-space', priority: 0.75, changeFrequency: 'monthly' as const },
    { url: '/case-studies/training-studio', priority: 0.75, changeFrequency: 'monthly' as const },
  ]

  // Blog hub pages (NEW - high priority for SEO)
  const blogHubPages = [
    { url: '/blog', priority: 0.9, changeFrequency: 'daily' as const },
    { url: '/blog/santa-cruz-business', priority: 0.85, changeFrequency: 'weekly' as const },
    { url: '/blog/team-leadership', priority: 0.85, changeFrequency: 'weekly' as const },
    { url: '/blog/systems-operations', priority: 0.85, changeFrequency: 'weekly' as const },
    { url: '/blog/ai-technology', priority: 0.85, changeFrequency: 'weekly' as const },
    { url: '/blog/growth-scaling', priority: 0.85, changeFrequency: 'weekly' as const },
    { url: '/blog/productivity-time-management', priority: 0.85, changeFrequency: 'weekly' as const },
    { url: '/blog/client-experience', priority: 0.85, changeFrequency: 'weekly' as const },
  ]

  // Individual blog posts (lower priority but important for SEO)
  const blogPosts = [
    // Santa Cruz Business Challenges (NEW)
    '/blog/santa-cruz-business-challenges',
    '/blog/survive-winter-slow-season-santa-cruz',
    '/blog/managing-cash-flow-tourist-off-season',
    '/blog/staffing-peak-summer-tourist-season-santa-cruz',
    '/blog/tourist-vs-local-customer-balance-santa-cruz',
    '/blog/building-local-loyalty-offset-tourist-dependency',
    '/blog/uc-santa-cruz-student-impact-on-business',
    '/blog/cant-find-reliable-employees-santa-cruz',
    '/blog/competing-with-tech-salaries-santa-cruz',
    '/blog/high-cost-of-living-makes-hiring-difficult-santa-cruz',
    '/blog/housing-crisis-attract-talent-santa-cruz',
    '/blog/training-high-turnover-service-industry-staff-santa-cruz',
    '/blog/revenue-good-no-profit-santa-cruz',
    '/blog/dont-understand-true-cost-per-service-product',
    '/blog/pricing-too-low-santa-cruz-cost-of-living',
    '/blog/cant-afford-pay-myself-owner-santa-cruz',
    '/blog/rent-increases-unsustainable-santa-cruz',
    '/blog/too-many-competitors-small-market-santa-cruz',
    '/blog/differentiating-in-crowded-santa-cruz-market',
    '/blog/big-chains-vs-local-business-competition-santa-cruz',
    '/blog/word-of-mouth-travels-fast-small-community-santa-cruz',
    '/blog/zero-marketing-budget-santa-cruz',
    '/blog/social-media-too-much-time-little-return',
    '/blog/google-my-business-optimization-santa-cruz',
    '/blog/yelp-google-reviews-santa-cruz-businesses',
    '/blog/getting-featured-good-times-local-press-santa-cruz',
    '/blog/which-local-events-worth-sponsoring-santa-cruz',
    '/blog/everything-takes-longer-than-it-should',
    '/blog/constantly-reinventing-processes-instead-of-systems',
    '/blog/manual-processes-should-be-automated',
    '/blog/cant-scale-operations-beyond-current-capacity',
    '/blog/handling-difficult-customers-small-community-santa-cruz',
    '/blog/should-i-open-second-location-optimize-current-santa-cruz',
    '/blog/growing-too-fast-losing-what-made-us-special-santa-cruz',
    '/blog/should-i-expand-to-online-ecommerce-santa-cruz',
    '/blog/when-to-transition-solopreneur-to-employer-santa-cruz',
    '/blog/website-outdated-cant-afford-redesign-santa-cruz',
    '/blog/california-employment-law-compliance-small-business',
    '/blog/which-pos-system-best-santa-cruz-retail',
    '/blog/do-i-need-crm-or-spreadsheet-enough',
    '/blog/online-review-response-strategy',
    // Santa Cruz Business Challenges - Batch 2 (NEW)
    '/blog/new-competitor-copying-our-model-santa-cruz',
    '/blog/competitors-undercutting-prices-santa-cruz',
    '/blog/online-competitors-hurting-local-retail-santa-cruz',
    '/blog/how-to-compete-without-being-cheapest-santa-cruz',
    '/blog/credit-card-processing-fees-eating-margins-santa-cruz',
    '/blog/mixing-personal-business-finances-santa-cruz',
    '/blog/email-marketing-feels-spammy-santa-cruz',
    '/blog/referral-program-not-generating-referrals-santa-cruz',
    '/blog/instagram-followers-dont-convert-paying-customers-santa-cruz',
    '/blog/equipment-breakdowns-disrupt-entire-day-santa-cruz',
    '/blog/inventory-shrinkage-waste-tracking-santa-cruz',
    '/blog/bringing-on-business-partner-vs-staying-solo-santa-cruz',
    '/blog/expanding-product-service-line-without-losing-focus-santa-cruz',
    // Santa Cruz Business Challenges - Batch 3 (NEW Seasonal/Operations)
    '/blog/predicting-seasonal-demand-inventory-planning-santa-cruz',
    '/blog/training-seasonal-employees-quickly-effectively-santa-cruz',
    '/blog/maintaining-service-quality-during-summer-rush-santa-cruz',
    '/blog/weekend-vs-weekday-staffing-optimization-santa-cruz',
    '/blog/holiday-season-planning-retail-restaurants-santa-cruz',
    '/blog/weather-dependent-business-planning-santa-cruz',
    '/blog/managing-rent-costs-during-slow-months-santa-cruz',
    '/blog/should-i-close-during-slow-season-or-stay-open-santa-cruz',
    '/blog/creating-year-round-revenue-streams-seasonal-businesses-santa-cruz',
    '/blog/employees-leave-for-higher-paying-bay-area-jobs-santa-cruz',
    '/blog/neighboring-businesses-inconsistent-hours-affect-foot-traffic-santa-cruz',
    '/blog/cant-find-anything-files-inventory-information-santa-cruz',
    '/blog/nextdoor-reputation-management-local-businesses-santa-cruz',
    // Santa Cruz Business Challenges - Batch 4 (NEW Hiring/Operations/Finance)
    '/blog/finding-bilingual-staff-diverse-customer-base-santa-cruz',
    '/blog/triple-booking-double-booking-appointments-santa-cruz',
    '/blog/when-to-invest-equipment-vs-making-do-current-santa-cruz',
    '/blog/understanding-break-even-point-new-services-santa-cruz',
    '/blog/managing-vendor-payment-terms-cash-flow-santa-cruz',
    '/blog/should-accept-cryptocurrency-alternative-payments-santa-cruz',
    '/blog/hiring-locals-vs-commuters-over-the-hill-santa-cruz',
    '/blog/part-time-vs-full-time-staffing-strategy-santa-cruz',
    '/blog/managing-employee-housing-challenges-santa-cruz',
    // Santa Cruz Business Challenges - Batch 5 (NEW Final Batch)
    '/blog/work-life-balance-expectations-santa-cruz-culture',
    '/blog/finding-employees-align-local-values-santa-cruz',
    '/blog/taking-too-long-close-out-daily-operations-santa-cruz',
    '/blog/supply-chain-delays-outside-major-metros-santa-cruz',
    '/blog/parking-challenges-affect-operations-deliveries-santa-cruz',
    '/blog/limited-space-requires-creative-operational-solutions-santa-cruz',
    '/blog/health-department-inspections-requirements-santa-cruz',
    '/blog/ada-compliance-older-santa-cruz-buildings',
    '/blog/business-license-permit-renewals-santa-cruz',
    '/blog/workers-comp-insurance-costs-claims-santa-cruz',
    '/blog/coastal-commission-regulations-beach-adjacent-businesses-santa-cruz',
    '/blog/food-handler-certifications-training-requirements-santa-cruz',
    '/blog/sales-tax-collection-remittance-confusion-santa-cruz',
    '/blog/scheduling-software-staff-will-actually-use-santa-cruz',
    '/blog/should-accept-apple-pay-contactless-payments-santa-cruz',
    '/blog/website-hosting-maintenance-costs-santa-cruz',
    '/blog/online-booking-system-vs-phone-bookings-santa-cruz',
    '/blog/wifi-internet-reliability-business-operations-santa-cruz',
    '/blog/cybersecurity-for-small-business-scams-hacking-santa-cruz',
    '/blog/dealing-with-entitled-tourist-customer-expectations-santa-cruz',
    '/blog/language-barriers-diverse-customer-base-santa-cruz',
    '/blog/accessibility-for-elderly-disabled-customers-santa-cruz',
    '/blog/setting-boundaries-customers-want-special-treatment-santa-cruz',
    '/blog/managing-customer-expectations-around-santa-cruz-time',
    '/blog/complaints-about-parking-location-access-santa-cruz',
    '/blog/return-refund-policy-for-services-santa-cruz',
    '/blog/creating-memorable-experiences-limited-resources-santa-cruz',
    '/blog/franchise-vs-independent-expansion-decision-santa-cruz',
    '/blog/multi-location-management-without-being-everywhere-santa-cruz',
    '/blog/building-team-support-growth-goals-santa-cruz',
    '/blog/outgrowing-current-space-cant-afford-bigger-rent-santa-cruz',
    // Original blog posts
    '/blog/ai-for-humans',
    '/blog/ai-for-santa-cruz-businesses',
    '/blog/automation-without-losing-personal-touch',
    '/blog/santa-cruz-boutique-fitness-operations',
    '/blog/santa-cruz-fitness-scheduling-nightmare',
    '/blog/santa-cruz-gym-membership-retention',
    '/blog/santa-cruz-fitness-client-communication',
    '/blog/santa-cruz-fitness-facilities-operations',
    '/blog/santa-cruz-wellness-business-intake',
    '/blog/santa-cruz-wellness-business-systems',
    '/blog/santa-cruz-wellness-industry-evolution',
    '/blog/restaurant-operations-santa-cruz',
    '/blog/retail-operations-santa-cruz',
    '/blog/creative-agencies-santa-cruz',
    '/blog/scaling-service-business-santa-cruz',
    '/blog/santa-cruz-small-business-operations',
    '/blog/sustainable-business-operations-santa-cruz',
    '/blog/meeting-overload-santa-cruz',
    '/blog/seasonal-business-operations',
    '/blog/team-asks-permission-everything',
    '/blog/decision-making-small-teams',
    '/blog/decisions-get-revisited',
    '/blog/team-autonomy-without-chaos',
    '/blog/delegate-but-still-doing-everything',
    '/blog/micromanaging-without-realizing',
    '/blog/founder-cant-take-vacation',
    '/blog/knowledge-in-founders-head',
    '/blog/repeating-same-questions',
    '/blog/documentation-that-actually-gets-used',
    '/blog/hiring-fixes-nothing',
    '/blog/new-hires-take-months',
    '/blog/good-people-bad-systems',
    '/blog/hiring-season-preparation',
    '/blog/team-waiting-for-answers',
    '/blog/team-siloed-not-collaborating',
    '/blog/information-scattered-everywhere',
    '/blog/quality-inconsistent-across-team',
    '/blog/quality-standards-not-documented',
    '/blog/team-working-late-accomplishing-less',
    '/blog/handoffs-where-work-dies',
    '/blog/waste-in-business-operations',
    '/blog/operational-sustainability-efficiency',
    '/blog/feedback-loops-dont-exist',
    '/blog/grew-past-informal-systems',
    '/blog/onboarding-bottleneck-local-business',
    '/blog/standard-operating-procedures-ignored',
    '/blog/data-privacy-ai-local-business',
    '/blog/too-many-tools-low-adoption',
    '/blog/crm-for-non-technical-owners',
    '/blog/growing-pains-feel-permanent',
    '/blog/growth-without-burnout',
    '/blog/sustainable-growth-versus-growth-at-all-costs',
    '/blog/building-business-that-lasts',
    '/blog/small-business-sustainability-paradox',
    '/blog/revenue-up-profits-flat',
    '/blog/lost-what-made-you-special',
    '/blog/busy-but-not-productive',
    '/blog/working-in-business-not-on',
    '/blog/urgent-always-beats-important',
    '/blog/reactive-not-proactive',
    '/blog/meetings-become-more-meetings',
    '/blog/calendar-owns-you',
    '/blog/context-switching-killing-productivity',
    '/blog/inbox-zero-myth',
    '/blog/async-communication-small-business',
    '/blog/client-work-versus-business-building',
    '/blog/first-impression-operational-failure',
    '/blog/client-expectations-misaligned',
    '/blog/client-experience-inconsistent',
    '/blog/consistency-secret-shopper-perspective',
    '/blog/25-years-secret-shopping-operations',
    '/blog/secret-shopping-small-business-insights',
    '/blog/secret-shopper-reveals-training-gaps',
    '/blog/employee-experience-secret-shopper',
    '/blog/client-retention-through-systems',
    '/blog/customer-experience-operations-disconnect',
    '/blog/culture-productivity-hack',
    '/blog/communication-breakdowns-constant',
    '/blog/scope-creep-every-project',
    '/blog/project-timelines-always-slip',
    '/blog/saying-yes-to-everything',
    '/blog/path-of-least-resistance',
    '/blog/why-business-feels-harder',
  ].map(url => ({ url, priority: 0.6, changeFrequency: 'monthly' as const }))

  // Resources pages
  const resourcesPages = [
    { url: '/resources/5-signs', priority: 0.75, changeFrequency: 'monthly' as const },
    { url: '/resources/10-minute-audit', priority: 0.75, changeFrequency: 'monthly' as const },
    { url: '/resources/delegation-framework', priority: 0.75, changeFrequency: 'monthly' as const },
  ]

  // Approach pages
  const approachPages = [
    { url: '/approach/human-centered-systems', priority: 0.7, changeFrequency: 'monthly' as const },
    { url: '/approach/safe-ai-enablement', priority: 0.7, changeFrequency: 'monthly' as const },
    { url: '/approach/tqm-principles', priority: 0.7, changeFrequency: 'monthly' as const },
  ]

  // Legal pages
  const legalPages = [
    { url: '/privacy-policy', priority: 0.3, changeFrequency: 'yearly' as const },
    { url: '/return-policy', priority: 0.3, changeFrequency: 'yearly' as const },
  ]

  // Combine all pages
  const allPages = [
    ...mainPages,
    ...servicesPages,
    ...packagesPages,
    ...caseStudiesPages,
    ...blogHubPages,
    ...blogPosts,
    ...resourcesPages,
    ...approachPages,
    ...legalPages,
  ]

  return allPages.map(({ url, priority, changeFrequency }) => ({
    url: `${base}${url}`,
    lastModified: new Date(),
    changeFrequency,
    priority,
  }))
}

